# fly.toml app configuration file generated for graphmlwebapp on 2023-09-13T15:32:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "graphmlwebapp"
primary_region = "sea"

[build]

[env]

[http_service]
  internal_port = 5002
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
