# fly.toml app configuration file generated for graphpost on 2023-09-10T08:56:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "graphtestrun"
primary_region = "sea"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
